name: Build Library

on:
  push:
    paths-ignore:
      - '**/*.md'
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    # 2019, has our .NET needs, latest does not
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    - name: Checkout LFS objects
      run: git lfs checkout
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Build
      run: dotnet build AssimpNet --configuration Release
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        path: .\AssimpNet\bin\Release\*
