name: Release & Publish

# When a release is published
on:
  release:
    types: [published]

jobs:
  build:
    # 2019, has our .NET needs, latest does not
    runs-on: windows-2019
    env:
      VERSION: ${{ github.event.release.tag_name }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Build
      run: dotnet build AssimpNet --configuration Release -p:Version=${{ env.VERSION }}
    - name: Push to Nuget
      run: dotnet nuget push .\AssimpNet\bin\Release\*.nupkg -k ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json