name: Release & Publish

# When a release is published
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.event.release.tag_name }}
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    - name: Checkout LFS objects
      run: git lfs checkout
    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Build & Pack
      run: |
        dotnet build AssimpNet -c Release
        dotnet pack AssimpNet -c Release -p:Version=${{ env.VERSION }}
    - name: Push to Nuget
      run: dotnet nuget push .\AssimpNet\bin\Release\*.nupkg -k ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json
